git:
  depth: 10
notifications:
  email: false

language: node_js
node_js:
  - "6"
os:
  - osx

before_install:
  - brew update
  - brew install gnu-tar libicns graphicsmagick xz
  - npm install -g bower
  - bower install
  - npm install

osx_image: xcode7.3

script: npm run pack-unix

branches:
  only:
  - master
